[build]
  command = "node scripts/build.js"
  publish = "dist"

# Admin panelinin SPA yönlendirmesi
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Ön yüz uygulamasının (index.html) SPA yönlendirmesi
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
