[build]
  command = "node scripts/build.js"
  publish = "dist" # Veya ön yüz dosyalarının olduğu klasör (örn: "public" veya "src")

# Admin panelinin düzgün çalışması için yönlendirme
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
